# Generated by Django 5.2 on 2025-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
