# Generated by Django 5.2 on 2025-09-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_email', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('teachers', 'Teachers Only'), ('parents', 'Parents Only')], default='everyone', max_length=20)),
                ('notify_assignments', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_grades', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Summary')], default='immediate', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('language', models.CharField(default='en', max_length=20)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('high_contrast', models.BooleanField(default=False)),
                ('allow_messages_from_students', models.BooleanField(default=True)),
                ('allow_messages_from_parents', models.BooleanField(default=True)),
                ('allow_group_chat', models.BooleanField(default=True)),
                ('default_grading_scheme', models.CharField(default='Percentage', max_length=50)),
                ('allow_late_submission', models.BooleanField(default=True)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
