# Generated by Django 5.2 on 2025-08-26 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('code', models.CharField(default='', max_length=100)),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
