# Generated by Django 5.2 on 2025-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_class_room_class_students_class_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
