# Generated by Django 5.2 on 2025-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='class_banners/'),
        ),
    ]
