# Generated by Django 5.2 on 2025-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_class_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
