# Generated by Django 5.2 on 2025-09-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_streamnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='instruction',
        ),
    ]
