# Generated by Django 5.2 on 2025-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_rename_description_assignment_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='instruction',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
