# Generated by Django 5.2 on 2025-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_rename_instruction_assignment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
