# Generated by Django 5.2 on 2025-09-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_submission_status_delete_chatcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamnotification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.assignment'),
        ),
    ]
