# Generated by Django 5.2 on 2025-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_streamnotification_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
