# Generated by Django 5.2 on 2025-09-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
