# Generated by Django 5.2 on 2025-09-21 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_streamnotification_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='student_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
