# Generated by Django 5.2 on 2025-10-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_quiz_description_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamnotification',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.quiz'),
        ),
    ]
