# Generated by Django 5.2 on 2025-10-03 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_assignmentvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentvideo',
            name='video_id',
        ),
        migrations.AddField(
            model_name='parentinvite',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
