# Generated by Django 5.2 on 2025-10-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_remove_assignmentvideo_video_id_parentinvite_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='children',
            new_name='students',
        ),
    ]
