# Generated by Django 5.2 on 2025-10-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0027_rename_children_parent_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.quiz'),
        ),
    ]
