# Generated by Django 5.2 on 2025-10-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_studentanswer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='theme',
        ),
        migrations.AddField(
            model_name='class',
            name='banner_color',
            field=models.CharField(default='#ffffff', help_text='HTML color code like #3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='class',
            name='drive_folder_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
