# Generated by Django 5.2 on 2025-10-05 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_remove_class_theme_class_banner_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='teachers.assignment')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
