# Generated by Django 5.2 on 2025-10-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_assignmentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('turned_in', 'Turned In'), ('missing', 'Missing')], default='assigned', max_length=20),
        ),
    ]
