# Generated by Django 5.2 on 2025-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled')], default='assigned', max_length=20),
        ),
    ]
