# Generated by Django 5.2 on 2025-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_assignment_scheduled_for_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamnotification',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamnotification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
