# Generated by Django 5.2 on 2025-10-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0037_attendance_session_attendancesession_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.attendancesession'),
        ),
    ]
