# Generated by Django 5.2 on 2025-10-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0038_alter_attendance_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(),
        ),
    ]
