# Generated by Django 5.2 on 2025-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0039_alter_attendancesession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
