# Generated by Django 5.2 on 2025-10-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0040_alter_attendancesession_expires_at_and_more'),
    ]

    operations = [
    ]
