# Generated by Django 5.2 on 2025-10-28 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0042_classcomment_privatecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='code',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius_m',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='teachers.class'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_from_class', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='teachers.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
