# Generated by Django 5.2 on 2025-10-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0043_remove_attendancesession_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamnotification',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.attendancesession'),
        ),
    ]
